[project]
name = "content-finder"
version = "3.0.0"
requires-python = ">=3.11"

[project.optional-dependencies]
dev = ["black", "isort", "flake8"]

[tool.flake8]
extend-ignore = ["E203", "E501", "W503"]

[tool.isort]
profile = "black"
